<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\I18n\Time;
use Cake\ORM\TableRegistry;

/**
 * Todos Controller
 *
 * @property \App\Model\Table\TodosTable $Todos
 */
class TodosController extends AppController
{

	public function initialize() {
		parent::initialize();
        $this->loadComponent('RequestHandler');
	}

	public function isAuthorized( $user ) {

		$perms = [
			'index' => [
				'volunteer' => true,
				'committee' => true,
				'admin' => true,
			],
			'me' => [
				'volunteer' => true,
				'committee' => true,
				'admin' => true,
			],
			'status' => [
				'volunteer' => true,
				'committee' => true,
				'admin' => true,
			],
			'view' => [
				'volunteer' => true,
				'committee' => true,
				'admin' => true,
			],
			'add' => [
				'volunteer' => false,
				'committee' => false,
				'admin' => true
			],
			'edit' => [
				'volunteer' => false,
				'committee' => true,
				'admin' => true
			]
		];

		if( isset( $perms[ $this->request->getParam('action') ][ $user['role'] ]) ) {
			return $perms[ $this->request->getParam('action') ][ $user['role'] ];
		}

		return parent::isAuthorized( $user ); // TODO: Change the autogenerated stub

		// committee members can see their todos.
		if(
			$user['role'] == 'committee' &&
		    in_array( $this->request->param('action'), ['index', 'me', 'status', 'view'] )
		) {
			return true;
		}

		return parent::isAuthorized( $user );
	}

	/**
	* redistributes todos among committee members
	* @param $user_id a user for whom work should be removed
	*/
	public function redistribute() {

		if( $this->request->is( ['post', 'patch', 'put'] ) ) {

		$Jobs = TableRegistry::get('Jobs');

		$jobs = $Jobs->find('all', [
			'conditions' => [
				'todos_complete' => 0
			],
			'contain' => ['Todos']
		]);

		foreach($jobs as $job) {
			$user = $this->getLeastBusyUser(); // defined in AppController
			foreach($job->todos as $todo) {
				$todo->user = $user;
				$this->Todos->save($todo);
			}

		}
		}
	}

	/**
	 * Index method
	 *
	 * @return \Cake\Network\Response|null
	 */
	public function index($who = 'me', $status = 'incomplete')
	{
		$paginate = [
			'contain' => ['Users','Jobs'],
			'order' => [
				'due' => 'ASC'
			]
		];

		if( 'me' == $who ) {
			$paginate['conditions']['Todos.user_id'] = $this->Auth->user('user_id');
		}
		
		if( 'incomplete' == $status ) {
			$paginate['conditions']['completed'] = false;
		}

		if( 'complete' == $status ) {
			$paginate['conditions']['completed'] = true;
		}

		if( 'overdue' == $status ) {
			$paginate['conditions']['due <'] = new Time();
		}

		$this->paginate = $paginate;
		$todos = $this->paginate($this->Todos);

		$this->set('request', $this->request);
		$this->set(compact('todos', 'who', 'status'));
		$this->set('_serialize', ['todos']);
	}

	public function me() {
		return $this->redirect([
			'action' => 'index',
			'me',
			'incomplete'
		]);
	}

	public function status($todo_id, $status) {
		$todo = null;
		if( in_array($status, ['complete', 'incomplete']) ) {
			$query = $this->Todos->find('all', [
				'conditions' => [
					"todo_id" => $todo_id,
					"user_id" => $this->Auth->user('user_id')
				]
			]);

			$todo = $query->first();
			if( $todo ) {
				$todo->completed = $status == "complete" ? true : false;
				if( ($result = $this->Todos->save($todo)) && $result ) {
					//
				} else {
					throw new InternalErrorException('Something happened with the server');
				}
			}
		}
		$this->set('todo', $todo);
		$this->set('_serialize', ['todo']);
	}

	/**
	 * View method
	 *
	 * @param string|null $id  id.
	 * @return \Cake\Network\Response|null
	 * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
	 */
	public function view($id = null)
	{
		$todo = $this->Todos->get($id, [
			'contain' => [ 'Users']
		]);

		$Model = TableRegistry::get($todo->model);
		$related_entity = $Model->get($todo->model_id);

		$this->set('todo', $todo);
		$this->set('related_entity', $related_entity);
		$this->set('_serialize', ['todo']);
	}

	/**
	 * Add method
	 *
	 * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
	 */
	public function add()
	{
		$todo = $this->Todos->newEntity();
		if ($this->request->is('post')) {
			$todo = $this->Todos->patchEntity($todo, $this->request->getData());
			if ($this->Todos->save($todo)) {
				$this->Flash->success(__('The todo has been saved.'));
				return $this->redirect(['action' => 'index']);
			} else {
				$this->Flash->error(__('The todo could not be saved. Please, try again.'));
			}
		}
		$todos = $this->Todos->Todos->find('list', ['limit' => 200]);
		$users = $this->Todos->Users->find('list', ['limit' => 200]);
		$this->set(compact('todo', 'todos', 'users'));
		$this->set('_serialize', ['todo']);
	}

	/**
	 * Edit method
	 *
	 * @param string|null $id id.
	 * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
	 * @throws \Cake\Network\Exception\NotFoundException When record not found.
	 */
	public function edit($id = null)
	{
		$todo = $this->Todos->get($id, [
			'contain' => []
		]);

		if ($this->request->is(['patch', 'post', 'put'])) {
			$todo = $this->Todos->patchEntity($todo, $this->request->getData());
			if ($this->Todos->save($todo)) {
				$this->Flash->success(__('The todo has been saved.'));
				return $this->redirect(['action' => 'index']);
			} else {
				$this->Flash->error(__('The todo could not be saved. Please, try again.'));
			}
		}
		//$todos = $this->Todos->Todos->find('list', ['limit' => 200]);
		$users = $this->Todos->Users->find('list', ['conditions' => [
			'role IS NOT' => 'volunteer' 
		]]);
		$this->set(compact('todo', 'jobs', 'users'));
		$this->set('_serialize', ['todo']);
	}

	/**
	 * Delete method
	 *
	 * @param string|null $id todo_id.
	 * @return \Cake\Network\Response|null Redirects to index.
	 * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
	 */
	public function delete($id = null)
	{
		$this->request->allowMethod(['post', 'delete']);
		$todo = $this->Todos->get($id);
		if ($this->Todos->delete($todo)) {
			$this->Flash->success(__('The todo has been deleted.'));
		} else {
			$this->Flash->error(__('The todo could not be deleted. Please, try again.'));
		}
		return $this->redirect(['action' => 'index']);
	}
}
